# Generated by Django 4.1.3 on 2022-11-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=20)),
                ('telefono', models.IntegerField(max_length=20)),
                ('cumpleaños', models.DateField()),
            ],
        ),
    ]
