# Generated by Django 4.1.3 on 2022-11-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
