# Generated by Django 4.1.3 on 2022-11-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClase', '0002_alter_persona_edad_alter_persona_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='cumpleaños',
            new_name='cumpleanos',
        ),
    ]
