# Generated by Django 4.1.3 on 2022-11-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClase', '0003_rename_cumpleaños_persona_cumpleanos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='cumpleanos',
        ),
    ]
